MISP/misp-warninglists

tools/openresolverchecker.py
Is able to fetch the MISP warning list a say if there are some resolvers.
=> Checks for open resolvers in the list of IPs.

lists/microsoft-office365/list.json, lists/public-dns-v4/list.json, lists/public-dns-v6/list.json, tools/generate-publicdns.py
This PR fixes some warninglists  not using `matching_attributes`.
=> No attribute filtering

lists/rfc6598/list.json
Please let me know if this is fine...
=> RFC 6598 - Carrier- Grade NAT (CGN) devices

lists/eicar.com/list.json
Files downloaded from eicar.org
=> Hashes for EICAR, EICAR zip and EICAR 2x zip.

lists/whats-my-ip/list.json
Just to add checkip.amazonaws.com into WarningList
=> checkip.amazonaws.com added into warninglist

tools/adoc_warninglists.py
Hello, please check if you could use my converter to asciidoctor format!
Thanks!
=> Created a converter of MISP warning lists to asciidoctor format

lists/url-shortener/list.json, lists/whats-my-ip/list.json
- 3 new domains in whats-my-ip
- 1 new domain in url-shortener
=> [ADD] new domains for whats-my-ip section and url-shortener section

lists/whats-my-ip/list.json
- new domain for whats-my-ip section
- version bump 4 -> 5
=> [add] new domain for whats-my-ip section

lists/url-shortener/list.json
added the shortener of the german state rhineland-palatinate (rlp)
=> added the shortener of the german state rlp

lists/microsoft-office365-ip/list.json, lists/microsoft-office365/list.json
microsoft-office365 - updated name/description and changed type string to substring 
miscrosoft-office365-ip - updated name/description and renamed lists.json to list.json
=> A couple of office 365 list fixes

lists/university_domains/list.json
Remove / or http for some domains in university_domains list.
=> Transform URL to domains for few entries

lists/microsoft/list.json
I received false positives and detections for this domain. Thought it should added.
=> Added windowsupdate.com domain

lists/url-shortener/list.json
Added cutt.ly to the shortener warning list
=> Added domain cutt.ly

lists/covid/list.json
=> Arcgis whitelistening

README.md
Added Majestic Million to Readme
=> Added Majestic Million to Readme

lists/tranco10k/list.json
=> Fixed typo in list.json of Tranco10k

lists/google/list.json
adding forms.gle to the list. This is a short link for Google Forms managed by Google Firebase
=> adding forms.gle which is for google forms.

README.md, generate_all.sh
Thanks for accepting the PR for the addition of the Tenable Lists. This PR is to update the generate_all.sh to include the generate-tenable.py execution, as well as referencing Tenable in the README.md.
- Update generate_all.sh
- Update README.md
=> Updates to reflect addition of Tenable Warninglists

generate_all.sh, tools/generate_majestic-million.py
give the possibility to choose the number of website to process
=> chg: [majestic_million] numbers parameter

tools/generate_majestic-million.py, tools/generate_moz-top500.py
fix majestic_million and moz top500
=> fix: [generator] remove header

README.md
added description of captive portal detection list to the readme.md
=> Update README.md for captive portal detection hostnames list

tools/generate-cisco-umbrella-blockpage.py, tools/generator.py
Added static Cisco Umbrella Blockpage IPv4, IPv6 and a reverse DNS lookup to fetch the hostnames.
=> Cisco Umbrella Blockpages

lists/url-shortener/list.json
add new url shorteners
update to V12
=> V12 url shortener

tools/generate-digitalside.py
Small typo in digitalside description (extra double quote).
=> Fix typo in digitalside description
