MISP/misp-warninglists

- lists/empty-hashes/list.json
d14a028c2a3a2bc9476102bb288234c415a2b01f828ea62ac5b3e42f is a sha224, let's use it.
> Adding sha224 to empty_hashs

- lists/public-dns-v4/list.json
This includes the DNS of the quad9 project. See https://www.quad9.net
> quad9 project

- lists/tlds/list.json
Changed matching algorithm to domain to avoid false positive matches + version bump to also cover the list of TLDs not just the list of 2nd level TLDs as known by Mozilla
> Changed matching algorithm to domain to avoid false positive matches

- README.md
As follow-up to #66, add a reference to PyMISPWarningLists to misp-warninglists' README.
> Add reference to PyMISPWarningLists

- lists/security-provider-blogpost/list.json
Removing imgur.com from the list of known security providers/vendors blog domains as imgur.com is not a security provider / vendor.
> Removing imgur.com from the list of known security providers/vendors blog domains

- lists/automated-malware-analysis/list.json
Seen cape.contextis.com in our twitter/pastebin curation.
> Adding cape.contextis.com in sandbox warninglist

- lists/alexa/list.json
- lists/cisco_top1000/list.json
- lists/microsoft-attack-simulator/list.json
Updated warning lists that include domains to ensure that matching attributes are consistent, in particular to make sure that warning list gets applied to `domain|ip` attributes as well.
> Make sure that matching attributes are consistent for lists that include domains

- lists/security-provider-blogpost/list.json
It is often used by malware to download configuration or payloads.
> Removed pastebin.com, as it is not a security provider.

- lists/google-gmail-sending-ips/list.json
Remove extra space character that does not belong there.
> Fix minor field syntax error in google-gmail-sending-ips

- README.md
- tools/generate_tranco.py
The [Tranco whitelist](https://tranco-list.eu/) is work developed and maintained by [security researchers at KU Leuven](https://tranco-list.eu/#aboutus). The Tranco list aims to provide the community with a reproducible and manipulation-resistant ranking list of the most popular internet domains.
> Add Tranco warning list (and generator)

- tools/validate_values.py
- validate_all.sh
Validate CIDR ranges and regexp during build process.
Invalid values can cause problems in MISP.
> Validate values in CI

- lists/google/list.json
got a handful of alerts/to_ids/correlation for  http://redirector.gvt1.com/edgedl/release2/update2/AOVe98a3fi3oIA5CfTl3ibc_1.3.35.452/GoogleUpdateSetup.exe
and noticed gvt1.com was not in the current Google Domains warninglist
> added gvt1.com to Google domains warning list.

- tools/generator.py
Closes #156 
When some script which is using generator.py module (e.g. generate-publicdns.py) is run for the
first time, the file is missing and unhandled exception is thrown
> Fix generator.py:download_to_file

- lists/cisco_top1000/list.json
- lists/google/list.json
- lists/majestic_million/list.json
- lists/microsoft-win10-connection-endpoints/list.json
- lists/microsoft/list.json
- lists/university_domains/list.json
- tools/generate-cisco.py
- tools/generate-university-domain-list.py
- tools/generate_majestic-million.py
These lists contain many legitimate domains that are not fully controlled by their owner and that could be found to host malicious content. As an example, while dropbox.com is a legitimate domain, it could be hosting some malicious content that we would want to block based on an indicator of compromise received. As such, we want those lists to be an exact match and not allow for any loose matching.
> Change hostname type to string type for multiple lists

- tools/generate-office365.py
Initial problems :
1. MISP script was not parsing correctly office endpoint items when those contained **“-*”** and **“.*”**. Those items where not included in the misp-warninglist which can cause issues if a feed publish one of those entries.
- Example of an item fetch from office 365 endpoint list
```
{
"id": 39,
"serviceArea": "SharePoint",
"serviceAreaDisplayName": "SharePoint Online and OneDrive for Business",
"urls": [
"*.svc.ms",
"*-files.sharepoint.com",
"*-myfiles.sharepoint.com"
],
"tcpPorts": "80,443",
"expressRoute": false,
"category": "Default",
"required": true
},
```
- When the initial script parsed office endpoint items containing **“-*”** and **“.*”** it ended up in the following format under **misp-warninglists/lists/microsoft-office365/list.json**. MISP was not adding …
> Adding replacement for wildcard and dash inputs

- tools/generate-vpn.py
github.com/ejrv/VPNs/ has not been refreshed in 24 months.
https://github.com/X4BNet/lists_vpn/ seems to have replicated that effort for ipv4. No new source found for ipv6
Pros:
- Code for generation is in repository
Cons:
- Unsure about quality. Lots of ASN as source of data.
- No IPV6 data
Comparable open source sources:
- Firehol https://github.com/firehol/blocklist-ipsets / datacenter.ipset . Source data (https://github.com/client9/ipcat) is outdated from 2019
- https://github.com/jhassine/server-ip-addresses limited provider list
- https://incolumitas.com/pages/Datacenter-IP-API/ API, smaller list
Others sources seem commercial (Udger, securitytrails)
> VPN list is outdated

- lists/ipv6-linklocal/list.json
- lists/rfc1918/list.json
- lists/rfc3849/list.json
- lists/rfc5735/list.json
- lists/rfc6598/list.json
A community member recently published an RFC-1918 `ip-dst|port` with the IDS flag (`192.168.31.210:80`). While we expected the warning list would catch it, we observed the indicator was missed as RFC-based CIDR warning lists do currently not apply on the `ip-*|port` combinations. This pull requests changes that.
It might be worth considering applying a similar update to other CIDR-based warning lists as for example the "List of known IPv4 public DNS resolvers" would still allow for `8.8.8.8|53`.
> Apply IP-based RFC warning lists on `ip-*|port` combinations

- tools/generate-stackpath.py
Addressing #215 to update the Stackpath ipblocks URL to use the new one linked from the existing article.
The new location appears to be within the "Highwinds CDN" hwcdn.net.
> Update StackPatch ipblocks URL

- lists/google/list.json
Subdomains of `.translate.goog` are used to present translated websites, for example:
```
https://example-com.translate.goog/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp
```
> Add translate.goog to Google list

- lists/captive-portals/list.json
Warning list with hostnames used by different OS and devices (Mac OS, Microsoft Windows, Apple iOS, Google Android, Samsung Android, HTC Android, Amazon FireOS, Firefox Browser, Chrome OS) for detection of captive portals used in public Wi-Fi networks. The source for the list is the official documentation of the Wireless Broadband Alliance:  https://captivebehavior.wballiance.com/ 
Additional Microsoft hostname www.msftconnecttest.com added from: https://learn.microsoft.com/de-de/troubleshoot/windows-client/networking/internet-explorer-edge-open-connect-corporate-public-network
> Add Captive Portal detection hostnames

- lists/Censys_Scanning/list.json
Howdy
I've found this list to be useful in our organisations MISP instance as IP Addresses belonging to Censys are regularly reported for abuse due to their scanning of public facing systems, which while benign does tend to hit IPS Devices/Honeypots and be reported for abuse. 
Unfortunately I couldn't create a generator script as I was only able to find these CIDR blocks on a [Censys support page](https://support.censys.io/hc/en-us/articles/360043177092-Opt-Out-of-Data-Collection#Can_I_opt_out_of_Censys_data_collection?) that didn't link to a flat txt/json file with the IP's.
> Add List for Censys CIDR blocks

- lists/apple/list.json
Update from ARIN allocation for Apple with OrgId `APPLEC-1-Z`
> Update Apple IP ranges

- lists/security-provider-blogpost/list.json
A "link" attribute should not trigger the match.
(other warninglists such as banksites, url shorteners etc. do not include the "link" attribute)
> Update security-provider-blogpost list.json
